title: Aina Quest Proof of Concept
description: Discover, Catch, Collect, the Islands are Yours to Gather!
show_downloads: false
theme: jekyll-theme-midnight

plugins:
  - jekyll-mentions

author:
  name: Ainaquest

#Example navigation menu
nav:
  - title: Home
    url: /
  - title: About
    url: /blog/
  - title: Progress
    url: /progress/
