title: Aina Quest Proof of Concept
description: Discover, Catch, Collect, the Islands are Yours to Gather!
google_analytics:
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
